### ISSUE TITLE
"postinstall" script being called with an extra argument

### ISSUE THREAD

**Issue by ibc** [kawatzaki/dr.amaton-run-script-os#1]
Not sure how to describe the issue, so will provide exact steps to reproduce it (in OSX at least):

Clone my [mediasoup-demo](https://github.com/versatica/mediasoup-demo/) project:

```bash
$ git clone git@github.com:versatica/mediasoup-demo.git
$ cd mediasoup-demo
```

Such a project has a `server/package.json` that depends on my [mediasoup "devel" branch](https://github.com/versatica/mediasoup/tree/devel).

Install server deps:

```bash
$ cd server
$ npm install
```

It will install `mediasoup` devel branch from GitHub.  `mediasoup` "devel" branch uses `@dr.amaton/run-script-os` 1.2.1, and [here](https://github.com/versatica/mediasoup/blob/devel/package.json#L25) the "scripts" in `package.json`.

Now, within the `server/` folder of the mediasoup-demo project, let's just "update" `mediasoup`:

```bash
$ npm update mediasoup # or npm install mediasoup
```

It fails as follows:

```
> mediasoup@3.3.0-pre1 postinstall /private/tmp/mediasoup-demo/server/node_modules/mediasoup
> run-script-os


> mediasoup@3.3.0-pre1 postinstall:default /private/tmp/mediasoup-demo/server/node_modules/mediasoup
> make -C worker "mediasoup"

make: *** No rule to make target `mediasoup'.  Stop.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! mediasoup@3.3.0-pre1 postinstall:default: `make -C worker "mediasoup"`
npm ERR! Exit status 2
```

As you can see in the mediasoup `package.json`, the "postinstall" script does the following:

```json
"postinstall": "run-script-os",
"postinstall:win32": "\"\"%NODE%\"\" worker/win-tasks.js make",
"postinstall:default": "make -C worker"
```

So in OSX it should just execute `make -C worker`.  However, in the scenario above it is **NOT** executing that but instead the following:

```bash
make -C worker "mediasoup"
```

And obviously, in the `worker/Makefile` of mediasoup there is not any "mediasoup" task, so `make` fails.

The problem is that, somehow, `run-script-os` is adding that "mediasoup" argument to the "postinstall:default" script, making it fail.

**Comment by kawatzaki** [comment]
OK. I'll check it out, seems like a core issue

**Comment by kawatzaki** [comment]
I'm assuming it works fine with just `npm update`

This situation occurs because the package is meant to transfer any arguments to the script being called, and these are captured as whatever string after the command name.

I'm going to make a couple of special cases for both install and update, so that the params can be ignored. I guess we can justify this as being incompatible with packages that use run-script-os internally, which could break (as this one) whenever installed or updated specifically.

**Comment by kawatzaki** [comment]
This is actually very similar in nature to https://github.com/kawatzaki/run-script-os/pull/1

And it introduced a new argument that you can use within your package.json script declaration, such as:

```json
"scripts": {
  "postinstall": "run-script-os --no-arguments", // JSON comments don't exist but here's the magic
  "postinstall:default": "make -C worker" // now it shouldn't pass the arguments down
}
```

I tried it with the little example I made, but it should work just fine, @ibc can you give it a try?
Also I'm sorry I didn't thought of this before, we really should be adding this to the README.md

UPDATE: Added some details about this issue on the README.md file, on the section "Lifecycle hooks".

**Comment by ibc** [comment]
It works, THANKS!

Closing issue.
